#!/usr/bin/python3
err = 0
try:    
    import sys
    import os
    arg = len(sys.argv)
    if os.getuid() != 0:
        err = 1
        print("Diese Programm erfordert Root Rechte")
        sys.exit(1)
    arg = len(sys.argv)
    if arg < 2:
        print("Paketname muss angegeben werden")
        err = 1
        sys.exit(1)
    pakete = " ".join(sys.argv[1:])
    command = "apt-get remove --auto-remove " + pakete
        #print(command)
    os.system(command)
except:   
    if err == 1:
        sys.exit(1)
    else:
        print("Während des Entfernens ist ein Fehler aufgetreten")
