#!/usr/bin/env python3
import os
import sys
if os.getuid() != 0:
    print("Skript muss mit Root-Rechten laufen")
    sys.exit(1)
if len(sys.argv) < 2:
    print("Tool zum zurüksetzten des Plasmadesktops")
    print("Dies wird alle Einstellungen des Plasmadesktops zurüksetzten")
    print("Um nur den Cache zu leeren tippe: plasmareset --cache")
    inp = input("Fortfahen(j/n)? : ")
    if inp == "j":
        os.system("sudo rm -R ~/.cache/*")
        os.system("sudo rm -R ~/.config/plasma*")
        print("Einstellungen erfolgreich zurückgesetzt")
    else:
        print("Abbruch")
        sys.exit(0)
elif sys.argv[1] == "--cache":
    print("Tool zum zurücksetzten des Plasmadesktops")
    print("Dies wird den Cache des Plasmadesktops leeren")
    print("Um alle Einstellungen zurückzusetzen tippe: plasmareset")
    inp = input("Fortfahen(j/n)? : ")
    if inp == "j":
        os.system("sudo rm -R ~/.cache/*")
        print("Cache erfolgreich geleert")
    else:
        print("Abbruch")
        sys.exit(0)
elif sys.argv[1] != "--cache":
    print(sys.argv[1] + ": unbekanntes Argument")
