#!/usr/bin/env python3
import sys
import random
if len(sys.argv) < 2:
    print("Fehlende Operatoren")
    print("Anzahl der Durchläufe wird benötigt")
    print("Beispiel: random 15")
if len(sys.argv) >  1:
    a = sys.argv[1]
    a = int(a)
    for i in range(1,a):
        print(''.join(random.choice('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')), end='')
    print(''.join(random.choice('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')))